server:
  port: 8080

spring:
  data:
    mongodb:
      replositories:
        enabled: true
      uri: mongodb://localhost:27017/comics-encyclopedia-requests

app-config:
  services:

    super_hero_api:
      access_token: 2560039007408985
      base_url: https://superheroapi.com/api/${app-config.api.access_token}/

    comics_processing:
      base_url: http://localhost:8081/api/comics/