server:
  port: 8080

spring:
  data:
    mongodb:
      replositories:
        enabled: true
      uri: mongodb://localhost:27017/comics-encyclopedia-requests

app-config:
  services:
    super_hero_api:
      access_token: 2560039007408985
      base_url: https://superheroapi.com/api/${app-config.api.access_token}/
    comics_processing:
      base_url: http://localhost:8081/api/comics/

kafka:
  bootstrap-server: localhost:9092
  topic:
    dc-comics-request: dc_comics_request.topic
    dc-comics-response: dc_comics_response.topic
    marvel-comics-request: marvel_comics_request.topic
    marvel-comics-response: marvel_comics_response.topic
  consumer:
    group-id: comics_encyclopedia_group
    auto-offset-reset: earliest