server:
  port: 8080

spring:
  data:
    mongodb:
      repositories:
        enabled: true
      uri: mongodb://localhost:27017/comics-encyclopedia-requests

app-config:

  services:
    super_hero_api:
      access_token: ${SUPER_HERO_API_ACCESS_TOKEN}
      base_url: https://superheroapi.com/api/${app-config.super_hero_api.access_token}/
    comics_processor:
      base_url: http://localhost:8081/api/comics/

  schedulers:
    delete-data-every-hour: 0 0 */1 * * *

kafka:
  bootstrap-server: localhost:9092
  topic:
    dc-comics-request: dc_comics_request.topic
    dc-comics-response: dc_comics_response.topic
    marvel-comics-request: marvel_comics_request.topic
    marvel-comics-response: marvel_comics_response.topic
  consumer:
    group-id: comics_encyclopedia_group
    auto-offset-reset: earliest